# Generated by Django 5.1.6 on 2025-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcceptedTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_code", models.TextField()),
                ("title_name", models.TextField()),
                ("hindi_title", models.TextField()),
                ("register_serial_no", models.TextField()),
                ("regn_no", models.TextField()),
                ("owner_name", models.TextField()),
                ("state", models.TextField()),
                ("publication_city_district", models.TextField()),
                ("periodity", models.TextField()),
            ],
            options={
                "db_table": "accepted_titles",
            },
        ),
    ]
