# Generated by Django 5.1.6 on 2025-03-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_acceptedtitle_hindi_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acceptedtitle",
            name="periodity",
        ),
    ]
