# Generated by Django 5.1.6 on 2025-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_acceptedtitle_periodity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedtitle",
            name="owner_name",
            field=models.TextField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="acceptedtitle",
            name="state",
            field=models.TextField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="acceptedtitle",
            name="title_name",
            field=models.TextField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="acceptedtitle",
            index=models.Index(
                fields=["title_name"], name="accepted_ti_title_n_fe4880_idx"
            ),
        ),
    ]
